"""Markdown report generation."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import Config


def _md(df: pd.DataFrame, floatfmt: str = "{:,.4f}") -> str:
    if df is None or df.empty:
        return "_no data_\n"
    d = df.copy()
    for col in d.columns:
        if pd.api.types.is_float_dtype(d[col]):
            d[col] = d[col].map(lambda v: "" if pd.isna(v) else floatfmt.format(v))
        else:
            d[col] = d[col].map(lambda v: "" if pd.isna(v) else str(v))
    header = "| " + " | ".join(map(str, d.columns)) + " |"
    sep = "| " + " | ".join(["---"] * len(d.columns)) + " |"
    rows = ["| " + " | ".join(r) + " |" for r in d.astype(str).values.tolist()]
    return "\n".join([header, sep, *rows]) + "\n"


def build_report(results: dict, cfg: Config) -> Path:
    h = results["hypotheses"]
    d = results["design"]
    srm = results["srm"]
    primary = results["primary"]
    bayes = results["bayesian"]
    sec = results["secondary"]
    decision = results["decision"]

    design_rows = pd.DataFrame(
        {
            "Item": ["Primary metric", "Control", "Treatment", "H0", "H1",
                     "alpha", "target power", "Baseline rate",
                     "Sample size / group", "Detectable relative MDE"],
            "Value": [
                h["primary_metric"], h["control"], h["treatment"], h["H0"], h["H1"],
                h["alpha"], h["power"], f"{d['baseline_p']:.2%}",
                f"{d['sample_size']['n_per_group']:,.0f}",
                f"{d['detectable_mde']['relative_mde']:.2%}",
            ],
        }
    )

    primary_rows = pd.DataFrame(
        [
            {"Quantity": "Control rate", "Value": f"{primary['p_control']:.4%}"},
            {"Quantity": "Treatment rate", "Value": f"{primary['p_treatment']:.4%}"},
            {"Quantity": "Absolute difference", "Value": f"{primary['absolute_diff']:+.4%}"},
            {"Quantity": "Relative lift", "Value": f"{primary['relative_lift_pct']:+.2f}%"},
            {"Quantity": "95% CI (difference)", "Value": f"[{primary['ci_low']:+.4%}, {primary['ci_high']:+.4%}]"},
            {"Quantity": "z-statistic", "Value": f"{primary['z_stat']:.3f}"},
            {"Quantity": "p-value (two-sided)", "Value": f"{primary['p_value']:.4f}"},
            {"Quantity": "p-value (chi-square)", "Value": f"{primary['p_chi2']:.4f}"},
            {"Quantity": "p-value (Fisher exact)", "Value": f"{primary['p_fisher']:.4f}"},
            {"Quantity": "Cohen's h", "Value": f"{primary['cohens_h']:.4f}"},
            {"Quantity": "Statistically significant", "Value": str(primary["significant"])},
        ]
    )

    bayes_rows = pd.DataFrame(
        [
            {"Quantity": "Posterior mean (control)", "Value": f"{bayes['posterior_control_mean']:.4%}"},
            {"Quantity": "Posterior mean (treatment)", "Value": f"{bayes['posterior_treatment_mean']:.4%}"},
            {"Quantity": "P(treatment > control)", "Value": f"{bayes['prob_treatment_better']:.2%}"},
            {"Quantity": "Expected relative uplift", "Value": f"{bayes['expected_rel_uplift_pct']:+.2f}%"},
            {"Quantity": "95% credible interval (rel.)",
             "Value": f"[{bayes['ci_rel_low_pct']:+.2f}%, {bayes['ci_rel_high_pct']:+.2f}%]"},
            {"Quantity": "Expected loss if we ship treatment",
             "Value": f"{bayes['expected_loss_ship_treatment']:.5f}"},
        ]
    )

    lines = [
        "# A/B Test Analysis — Automated Report",
        "",
        "> Cookie Cats gate placement experiment (`gate_30` vs `gate_40`).",
        "> Generated by `python run.py`; figures in `reports/figures/`.",
        "",
        f"## 🏁 Decision: **{decision['verdict']}**",
        "",
        decision["rationale"],
        "",
        "## 1. Hypothesis & design",
        "",
        _md(design_rows, "{}"),
        "",
        f"**Sample-size calculation** — to detect a {d['sample_size']['relative_mde']:.1%} relative "
        f"change on a baseline of {d['sample_size']['baseline_p']:.2%} at α={h['alpha']} and "
        f"power={h['power']}, we would need **{d['sample_size']['n_per_group']:,.0f} users per group**.",
        "",
        "## 2. Randomisation health checks",
        "",
        _md(pd.DataFrame([srm]), "{}"),
        "",
        f"**SRM detected:** {srm['srm_detected']} "
        f"(observed split {1 - srm['observed_ratio']:.3%} / {srm['observed_ratio']:.3%}).",
        "",
        "Covariate balance:",
        "",
        _md(results["balance"], "{:.4%}"),
        "",
        f"Outliers above {cfg.get('experiment', 'outlier_threshold'):,} rounds: "
        f"**{len(results['outliers'])}** user(s).",
        "",
        "## 3. Primary metric — 7-day retention",
        "",
        _md(primary_rows, "{}"),
        "",
        f"Bootstrap 95% CI: [{results['bootstrap']['ci_low']:+.4%}, "
        f"{results['bootstrap']['ci_high']:+.4%}] with bootstrap p-value "
        f"**{results['bootstrap']['bootstrap_p_value']:.4f}**.",
        "",
        "![Retention rates](figures/02_retention_rates.png)",
        "",
        "![Bootstrap difference](figures/03_bootstrap_diff.png)",
        "",
        "## 4. Bayesian view",
        "",
        _md(bayes_rows, "{}"),
        "",
        "![Bayesian posteriors](figures/04_bayesian_posteriors.png)",
        "",
        "## 5. Secondary metrics",
        "",
        "**1-day retention**",
        "",
        _md(pd.DataFrame([sec["retention_1"]])[
            ["p_control", "p_treatment", "absolute_diff", "relative_lift_pct", "p_value", "significant"]
        ], "{}"),
        "",
        "**Game rounds** (non-parametric + bootstrap):",
        "",
        _md(pd.DataFrame([{**sec["gamerounds"], "ci_low": sec["gamerounds_bootstrap"]["ci_low"],
                           "ci_high": sec["gamerounds_bootstrap"]["ci_high"]}]), "{}"),
        "",
        "![Game rounds](figures/05_gamerounds.png)",
        "",
        "## 6. Power analysis",
        "",
        "![Power curve](figures/06_power_curve.png)",
        "",
        f"Achieved post-hoc power for the observed effect: "
        f"**{results['power']['achieved_power']:.2%}**.",
        "",
        "## 7. Methodology",
        "",
        "- **Primary test**: two-sided two-proportion z-test (Wald CI), confirmed with chi-square and Fisher's exact test.",
        "- **Bootstrap**: binomial resampling for proportions; index resampling for means.",
        "- **Bayesian**: Beta(1,1) priors → Beta-Binomial posteriors; decisions use P(B>A) and expected loss.",
        "- **SRM**: chi-square goodness-of-fit against a 50/50 expected split.",
        "",
    ]

    out = cfg.path("paths", "report")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
